### PR TITLE
ci: fix Version Packages for releases

### PR DESCRIPTION
**Pull request by causaly-mark**
Add new changeset release token, bump `@changesets/release` version

### CODE REVIEW

**Comment by causaly-mark** [comment]
For context: https://causaly.atlassian.net/browse/CSLY-8838

**Review by thanoskrg — APPROVED** [review]
Thanks @causaly-mark , let's wait for @jmike to have a look at this one please before merging 🙏

**Comment by causaly-mark** [comment]
In addition to the code, we need to ensure the CHANGESET_RELEASE_TOKEN is present in repo secrets (under actions -> repository secrets). I'm pretty sure I added it, but I can't check now.

**Review by jmike — APPROVED** [review]
Good to go. The secret is already defined.

**Pull request merged**
