### PR TITLE
Add "types" to package export

### PR DESCRIPTION
**Pull request by kkirby**
Per https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

### CODE REVIEW

**Review by nikoskalogridis — APPROVED** [review]
Thank you

**Comment by ivan-kleshnin** [comment]
"module": "path-to-esm" has to be added as well to unblock ESM-based project to use this library 🤔

**Comment by kkirby** [comment]
@ivan-kleshnin This seems out of scope from this PR. Aside, I went down a rabbit hole looking into your suggestion and this is what I found:

1. The `"module"` field isn't actually supported by NodeJS, and instead they settled on using `"exports"`:
  https://stackoverflow.com/a/42817320/701263
2. It seems most people agree that a package shouldn't duplicate the source code for different module resolutions. Instead, you should target CJS, and then have some kind of wrapper for MJS. I'm not sure how that would work.
3. If you wanted to still compile it to both, you'd need to do some things:
    1. Update all the `.ts` files to import their dependencies using `.js`. The files can remain `.ts`, but the output files will include the `.js` extension, which is required by NodeJS when using ESM: 
    https://nodejs.org/api/esm.html#mandatory-file-extensions
    2. Provide a `package.json` file in the `build/node/esm` and `build/node/cjs` folder that contain the following:
      ```json
      {
        "type": "module"
      }
      ```
      and
      ```json
      {
        "type": "commonjs"
      }
      ```
    3. That should be it. NodeJS will correctly require and import the module. It's just annoying that you have to import using `.js` in the `.ts` files.
 
For more information, check out this lengthly discussion: https://github.com/microsoft/TypeScript/issues/18442

**Comment by ivan-kleshnin** [comment]
@kkirby thanks for the response! It's a very complex topic and I'm far from being an expert there. I can only add the following points:

1. `zod-validation-error` is one of very few libraries that don't work within my TS/ESM setup. So I assume something is not right here, not on my side.
2. I don't use file extensions as it's possible to omit them in modern TS/ESM, in NodeJS at least. Here's a relevant part of my **client-side** tsconfig:

```json
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "compilerOptions": {
    "lib": ["esnext", "dom"],
    "baseUrl": ".",
    "module": "esnext",
    "target": "esnext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "typeRoots": [
      "./node_modules/@types",
      "./lib/typings"
    ]
  },
  "include": [
    "**/*.ts",
    "**/*.tsx",
    "**/*.d.ts"
  ],
  "ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node"
  }
}
```

**Comment by dimitrisnl** [comment]
Hey, @ivan-kleshnin I want to take a closer look at this problem. Would you mind opening an issue? Let's move the discussion there so we can unblock this PR.

**Comment by ivan-kleshnin** [comment]
> Hey, @ivan-kleshnin I want to take a closer look at this problem. Would you mind opening an issue? Let's move the discussion there so we can unblock this PR.

Sure, I'll open a dedicated issue, thank you!

**Comment by dimitrisnl** [comment]
Hey, I opened a new [PR](https://github.com/causaly/zod-validation-error/pull/8) that will, unfortunately, make this one obsolete. 

I apologize for this but thank you for bringing these issues to my attention. We've decided to drop `swc` and the `exports` key. WIll revisit it in the future, but it seems that ESM works properly now.

**Pull request closed without merging**
